### ISSUE TITLE
example_handel.m fails to plot scattergram

### ISSUE THREAD

**Issue by jfsantos** [lostanlen/scattering.m#35]
`example_handel.m` is currently breaking at line 31:

```
>> example_handel
Index exceeds matrix dimensions.

Error in example_handel (line 31)
scattergram = U{1+2}.data{modulation_scale_index}.';
```

 `modulation_scale_index` is 8, but `data` has only 4 elements. Also, `data` is a 3D array, so the transpose operator is not defined.

**Comment by lostanlen** [comment]
Hi,
Yes, I have noticed the issue today.
One must call
`U = sc_unchunk{U}`
in order to collapse the first two dimensions (time withing chunk and chunk index) into one time dimension.
The fact that data has only 4 elements may be a mistake in bandwidth inequality. Will keep you in touch.

**Comment by lostanlen** [comment]
I think the inequality was correct. The issue should be fixed after PR #34. Thank you @jfsantos for your interest.

**Comment by jfsantos** [comment]
It works now, thanks! Just a small nitpick: line 35 plots the scattergram _over_ the scalogram, so maybe it would be better to create a new figure before calling imagesc. It's also not clear why you call `display_scalogram` twice, the second time after some simple variable manipulation. I guess it's probably there for debugging reasons.

**Comment by lostanlen** [comment]
Both remarks are right. Commits 2a77296 and aec2c51 on latest master address them. I have put the two figures as vertical subplots.

**Comment by jfsantos** [comment]
That was quick, thanks!
